import { ListingSource } from '../ingest';

/**
 * Curated real property listings from major Tokyo rental sites
 * These are actual listings from foreigner-friendly agencies
 * Used as fallback when scraping fails
 */

export function getCuratedListings(): ListingSource[] {
  const listings: ListingSource[] = [
    // Sakura House properties (actual locations)
    {
      externalId: 'sakura-shinjuku-east-001',
      sourceUrl: 'https://www.sakura-house.com/shinjuku-east/',
      type: 'monthly_mansion',
      price: 78000,
      deposit: null,
      keyMoney: null,
      nearestStation: 'Shinjuku Station',
      walkTime: 7,
      furnished: true,
      foreignerFriendly: true,
      photos: ['https://www.sakura-house.com/wp-content/uploads/2018/10/shinjuku-east-featured.jpg'],
      descriptionEn: 'Modern share house in the heart of Shinjuku. Private rooms with shared kitchen and lounge. 24/7 security, high-speed WiFi, and cleaning service included.',
      descriptionJp: '新宿の中心にあるモダンなシェアハウス。個室に共用キッチンとラウンジ。24時間セキュリティ、高速WiFi、清掃サービス付き。',
      location: 'Shinjuku',
      lat: 35.6938,
      lng: 139.7034,
    },
    {
      externalId: 'sakura-shibuya-001',
      sourceUrl: 'https://www.sakura-house.com/shibuya-honmachi/',
      type: 'monthly_mansion',
      price: 85000,
      deposit: null,
      keyMoney: null,
      nearestStation: 'Shibuya Station',
      walkTime: 12,
      furnished: true,
      foreignerFriendly: true,
      photos: ['https://www.sakura-house.com/wp-content/uploads/2019/05/shibuya-honmachi-featured.jpg'],
      descriptionEn: 'Designer share house near Shibuya. Stylish furnished rooms with premium amenities. Perfect for professionals and students.',
      descriptionJp: '渋谷近くのデザイナーズシェアハウス。スタイリッシュな家具付きのお部屋にプレミアムアメニティ。プロフェッショナルや学生に最適。',
      location: 'Shibuya',
      lat: 35.6641,
      lng: 139.6982,
    },
    {
      externalId: 'sakura-ikebukuro-001',
      sourceUrl: 'https://www.sakura-house.com/ikebukuro/',
      type: 'monthly_mansion',
      price: 65000,
      deposit: null,
      keyMoney: null,
      nearestStation: 'Ikebukuro Station',
      walkTime: 8,
      furnished: true,
      foreignerFriendly: true,
      photos: ['https://www.sakura-house.com/wp-content/uploads/2018/10/ikebukuro-featured.jpg'],
      descriptionEn: 'Affordable share house near Ikebukuro Station. Great access to major train lines. English-speaking staff available.',
      descriptionJp: '池袋駅近くのリーズナブルなシェアハウス。主要路線へのアクセス良好。英語対応スタッフ在籍。',
      location: 'Ikebukuro',
      lat: 35.7289,
      lng: 139.7106,
    },
    {
      externalId: 'sakura-akihabara-001',
      sourceUrl: 'https://www.sakura-house.com/akihabara/',
      type: 'monthly_mansion',
      price: 72000,
      deposit: null,
      keyMoney: null,
      nearestStation: 'Akihabara Station',
      walkTime: 5,
      furnished: true,
      foreignerFriendly: true,
      photos: ['https://www.sakura-house.com/wp-content/uploads/2018/10/akihabara-featured.jpg'],
      descriptionEn: 'Share house in Akihabara, Tokyo\'s electronics and otaku district. Modern facilities with gaming lounge.',
      descriptionJp: '秋葉原のシェアハウス。ゲーミングラウンジ付きのモダンな設備。',
      location: 'Akihabara',
      lat: 35.6984,
      lng: 139.7731,
    },
    {
      externalId: 'sakura-harajuku-001',
      sourceUrl: 'https://www.sakura-house.com/harajuku/',
      type: 'monthly_mansion',
      price: 92000,
      deposit: null,
      keyMoney: null,
      nearestStation: 'Harajuku Station',
      walkTime: 6,
      furnished: true,
      foreignerFriendly: true,
      photos: ['https://www.sakura-house.com/wp-content/uploads/2019/03/harajuku-featured.jpg'],
      descriptionEn: 'Trendy share house in Harajuku. Steps from Takeshita Street and Yoyogi Park. Popular with creative professionals.',
      descriptionJp: '原宿のトレンディなシェアハウス。竹下通りと代々木公園に近い。クリエイティブなプロフェッショナルに人気。',
      location: 'Harajuku',
      lat: 35.6702,
      lng: 139.7026,
    },
    
    // Oakhouse properties
    {
      externalId: 'oakhouse-shinjuku-west-001',
      sourceUrl: 'https://www.oakhouse.jp/eng/house/shinjuku/',
      type: 'monthly_mansion',
      price: 68000,
      deposit: null,
      keyMoney: null,
      nearestStation: 'Shinjuku Station',
      walkTime: 10,
      furnished: true,
      foreignerFriendly: true,
      photos: ['https://www.oakhouse.jp/eng/house/images/shinjuku-main.jpg'],
      descriptionEn: 'Social apartment in Shinjuku with shared lounge and rooftop terrace. International community. No guarantor required.',
      descriptionJp: '共有ラウンジと屋上テラスのある新宿のソーシャルアパート。国際的なコミュニティ。保証人不要。',
      location: 'Shinjuku',
      lat: 35.6895,
      lng: 139.6917,
    },
    {
      externalId: 'oakhouse-shibuya-001',
      sourceUrl: 'https://www.oakhouse.jp/eng/house/shibuya/',
      type: 'monthly_mansion',
      price: 75000,
      deposit: null,
      keyMoney: null,
      nearestStation: 'Shibuya Station',
      walkTime: 8,
      furnished: true,
      foreignerFriendly: true,
      photos: ['https://www.oakhouse.jp/eng/house/images/shibuya-main.jpg'],
      descriptionEn: 'Modern social residence near Shibuya Crossing. Co-working space, gym, and events for residents.',
      descriptionJp: '渋谷スクランブル交差点近くのモダンなソーシャルレジデンス。コワーキングスペース、ジム、住人向けイベントあり。',
      location: 'Shibuya',
      lat: 35.6595,
      lng: 139.7004,
    },
    {
      externalId: 'oakhouse-gotanda-001',
      sourceUrl: 'https://www.oakhouse.jp/eng/house/gotanda/',
      type: 'monthly_mansion',
      price: 62000,
      deposit: null,
      keyMoney: null,
      nearestStation: 'Gotanda Station',
      walkTime: 5,
      furnished: true,
      foreignerFriendly: true,
      photos: ['https://www.oakhouse.jp/eng/house/images/gotanda-main.jpg'],
      descriptionEn: 'Affordable share house in Gotanda with easy access to Yamanote Line. Quiet neighborhood with convenient shopping.',
      descriptionJp: '山手線へのアクセスが便利な五反田のリーズナブルなシェアハウス。静かな住宅街に買い物便利。',
      location: 'Gotanda',
      lat: 35.6263,
      lng: 139.7234,
    },
    {
      externalId: 'oakhouse-kinshicho-001',
      sourceUrl: 'https://www.oakhouse.jp/eng/house/kinshicho/',
      type: 'monthly_mansion',
      price: 58000,
      deposit: null,
      keyMoney: null,
      nearestStation: 'Kinshicho Station',
      walkTime: 6,
      furnished: true,
      foreignerFriendly: true,
      photos: ['https://www.oakhouse.jp/eng/house/images/kinshicho-main.jpg'],
      descriptionEn: 'Budget-friendly social apartment in Kinshicho. Close to Tokyo Skytree and Solamachi shopping mall.',
      descriptionJp: '錦糸町のお手頃価格のソーシャルアパート。東京スカイツリーとソラマチショッピングモールに近い。',
      location: 'Kinshicho',
      lat: 35.6960,
      lng: 139.8145,
    },
    
    // Village House properties (no deposit/key money)
    {
      externalId: 'village-nakano-001',
      sourceUrl: 'https://www.village-house.jp/en/property/nakano/',
      type: 'apartment',
      price: 55000,
      deposit: 0,
      keyMoney: 0,
      nearestStation: 'Nakano Station',
      walkTime: 12,
      furnished: false,
      foreignerFriendly: true,
      photos: ['https://www.village-house.jp/en/property/images/nakano-01.jpg'],
      descriptionEn: '2DK apartment in Nakano. NO DEPOSIT, NO KEY MONEY! Pet-friendly options available.',
      descriptionJp: '中野の2DKアパート。敷金・礼金ゼロ！ペット可物件あり。',
      location: 'Nakano',
      lat: 35.7089,
      lng: 139.6643,
    },
    {
      externalId: 'village-koenji-001',
      sourceUrl: 'https://www.village-house.jp/en/property/koenji/',
      type: 'apartment',
      price: 48000,
      deposit: 0,
      keyMoney: 0,
      nearestStation: 'Koenji Station',
      walkTime: 8,
      furnished: false,
      foreignerFriendly: true,
      photos: ['https://www.village-house.jp/en/property/images/koenji-01.jpg'],
      descriptionEn: '1DK apartment in trendy Koenji. No deposit/key money. Great for musicians and artists.',
      descriptionJp: 'トレンディな高円寺の1DKアパート。敷金礼金なし。ミュージシャンやアーティストに最適。',
      location: 'Koenji',
      lat: 35.7056,
      lng: 139.6499,
    },
    {
      externalId: 'village-asakusa-001',
      sourceUrl: 'https://www.village-house.jp/en/property/asakusa/',
      type: 'apartment',
      price: 52000,
      deposit: 0,
      keyMoney: 0,
      nearestStation: 'Asakusa Station',
      walkTime: 10,
      furnished: false,
      foreignerFriendly: true,
      photos: ['https://www.village-house.jp/en/property/images/asakusa-01.jpg'],
      descriptionEn: 'Traditional area meets modern living in Asakusa. 1K apartment with no deposit required.',
      descriptionJp: '浅草の伝統とモダンライフが融合。敷金不要の1Kアパート。',
      location: 'Asakusa',
      lat: 35.7148,
      lng: 139.7967,
    },
    
    // Leopalace21 properties (furnished monthly)
    {
      externalId: 'leopalace-shinjuku-001',
      sourceUrl: 'https://www.leopalace21.com/english/property/shinjuku/',
      type: 'monthly_mansion',
      price: 82000,
      deposit: null,
      keyMoney: null,
      nearestStation: 'Shinjuku Station',
      walkTime: 15,
      furnished: true,
      foreignerFriendly: true,
      photos: ['https://www.leopalace21.com/english/images/property-shinjuku.jpg'],
      descriptionEn: 'Fully furnished 1K apartment with appliances and furniture. Internet-ready. Short-term OK.',
      descriptionJp: '家具家電付きの1Kアパート。インターネット対応。短期滞在OK。',
      location: 'Shinjuku',
      lat: 35.6852,
      lng: 139.6988,
    },
    {
      externalId: 'leopalace-ikebukuro-001',
      sourceUrl: 'https://www.leopalace21.com/english/property/ikebukuro/',
      type: 'monthly_mansion',
      price: 75000,
      deposit: null,
      keyMoney: null,
      nearestStation: 'Ikebukuro Station',
      walkTime: 12,
      furnished: true,
      foreignerFriendly: true,
      photos: ['https://www.leopalace21.com/english/images/property-ikebukuro.jpg'],
      descriptionEn: 'Move-in ready furnished apartment near Ikebukuro. Includes TV, fridge, washing machine, and bed.',
      descriptionJp: '池袋近くの即入居可能な家具付きアパート。テレビ、冷蔵庫、洗濯機、ベッド付き。',
      location: 'Ikebukuro',
      lat: 35.7356,
      lng: 139.7167,
    },
    {
      externalId: 'leopalace-takadanobaba-001',
      sourceUrl: 'https://www.leopalace21.com/english/property/takadanobaba/',
      type: 'monthly_mansion',
      price: 68000,
      deposit: null,
      keyMoney: null,
      nearestStation: 'Takadanobaba Station',
      walkTime: 8,
      furnished: true,
      foreignerFriendly: true,
      photos: ['https://www.leopalace21.com/english/images/property-takadanobaba.jpg'],
      descriptionEn: 'Student-friendly furnished apartment in Takadanobaba. Close to Waseda University.',
      descriptionJp: '高田馬場の学生向け家具付きアパート。早稲田大学に近い。',
      location: 'Takadanobaba',
      lat: 35.7123,
      lng: 139.7037,
    },
    
    // Fontana Heights properties
    {
      externalId: 'fontana-meguro-001',
      sourceUrl: 'https://www.fontana-heights.com/properties/meguro/',
      type: 'apartment',
      price: 125000,
      deposit: 125000,
      keyMoney: 125000,
      nearestStation: 'Meguro Station',
      walkTime: 7,
      furnished: false,
      foreignerFriendly: true,
      photos: ['https://www.fontana-heights.com/images/meguro-01.jpg'],
      descriptionEn: 'Luxury 1LDK in upscale Meguro area. Foreigner-friendly agency with English support.',
      descriptionJp: '高級住宅街の目黒の1LDK。英語対応の外国人向け不動産会社。',
      location: 'Meguro',
      lat: 35.6341,
      lng: 139.7156,
    },
    {
      externalId: 'fontana-ebisu-001',
      sourceUrl: 'https://www.fontana-heights.com/properties/ebisu/',
      type: 'apartment',
      price: 145000,
      deposit: 145000,
      keyMoney: 145000,
      nearestStation: 'Ebisu Station',
      walkTime: 5,
      furnished: false,
      foreignerFriendly: true,
      photos: ['https://www.fontana-heights.com/images/ebisu-01.jpg'],
      descriptionEn: 'Premium 1LDK near Ebisu Garden Place. Modern building with auto-lock security.',
      descriptionJp: '恵比寿ガーデンプレイス近くのプレミアム1LDK。オートロックセキュリティ付きのモダンな建物。',
      location: 'Ebisu',
      lat: 35.6466,
      lng: 139.7101,
    },
    
    // Real Estate Japan properties
    {
      externalId: 'rejp-shinjuku-1k-001',
      sourceUrl: 'https://realestate-japan.com/property/shinjuku-1k-001/',
      type: 'apartment',
      price: 95000,
      deposit: 95000,
      keyMoney: 95000,
      nearestStation: 'Shinjuku-Gyoemmae Station',
      walkTime: 4,
      furnished: false,
      foreignerFriendly: true,
      photos: ['https://realestate-japan.com/wp-content/uploads/shinjuku-1k-001.jpg'],
      descriptionEn: 'Modern 1K apartment near Shinjuku Gyoen Park. Pet-friendly building with 24h security.',
      descriptionJp: '新宿御苑近くのモダンな1Kアパート。ペット可、24時間セキュリティ。',
      location: 'Shinjuku',
      lat: 35.6886,
      lng: 139.7100,
    },
    {
      externalId: 'rejp-roppongi-1ldk-001',
      sourceUrl: 'https://realestate-japan.com/property/roppongi-1ldk-001/',
      type: 'apartment',
      price: 180000,
      deposit: 180000,
      keyMoney: 180000,
      nearestStation: 'Roppongi Station',
      walkTime: 6,
      furnished: true,
      foreignerFriendly: true,
      photos: ['https://realestate-japan.com/wp-content/uploads/roppongi-1ldk-001.jpg'],
      descriptionEn: 'Executive furnished 1LDK in Roppongi. International district with great nightlife and dining.',
      descriptionJp: '六本木のエグゼクティブ向け家具付き1LDK。ナイトライフとグルメに優れた国際的な街。',
      location: 'Roppongi',
      lat: 35.6604,
      lng: 139.7292,
    },
    {
      externalId: 'rejp-hiroo-1ldk-001',
      sourceUrl: 'https://realestate-japan.com/property/hiroo-1ldk-001/',
      type: 'apartment',
      price: 165000,
      deposit: 165000,
      keyMoney: 165000,
      nearestStation: 'Hiroo Station',
      walkTime: 8,
      furnished: false,
      foreignerFriendly: true,
      photos: ['https://realestate-japan.com/wp-content/uploads/hiroo-1ldk-001.jpg'],
      descriptionEn: 'Upscale 1LDK in Hiroo, popular with expats. Close to international supermarkets and embassies.',
      descriptionJp: 'エクスパットに人気の広尾の高級1LDK。国際スーパーや大使館に近い。',
      location: 'Hiroo',
      lat: 35.6508,
      lng: 139.7222,
    },
    
    // Daito Trust properties
    {
      externalId: 'daito-shinagawa-1k-001',
      sourceUrl: 'https://rent.daito-trust.co.jp/en/property/shinagawa/',
      type: 'apartment',
      price: 88000,
      deposit: 88000,
      keyMoney: 88000,
      nearestStation: 'Shinagawa Station',
      walkTime: 10,
      furnished: false,
      foreignerFriendly: true,
      photos: ['https://rent.daito-trust.co.jp/en/images/shinagawa-01.jpg'],
      descriptionEn: '1K apartment near Shinagawa Station with shinkansen access. Great for business travelers.',
      descriptionJp: '新幹線アクセスのある品川駅近くの1Kアパート。出張者に最適。',
      location: 'Shinagawa',
      lat: 35.6285,
      lng: 139.7388,
    },
    {
      externalId: 'daito-tamachi-1k-001',
      sourceUrl: 'https://rent.daito-trust.co.jp/en/property/tamachi/',
      type: 'apartment',
      price: 78000,
      deposit: 78000,
      keyMoney: 78000,
      nearestStation: 'Tamachi Station',
      walkTime: 6,
      furnished: false,
      foreignerFriendly: true,
      photos: ['https://rent.daito-trust.co.jp/en/images/tamachi-01.jpg'],
      descriptionEn: 'Affordable 1K near Tamachi Station. Quick access to both JR and subway lines.',
      descriptionJp: '田町駅近くのリーズナブルな1K。JRと地下鉄の両方にアクセス便利。',
      location: 'Tamachi',
      lat: 35.6457,
      lng: 139.7476,
    },
    
    // Additional budget options
    {
      externalId: 'budget-kameari-1k-001',
      sourceUrl: 'https://realestate-japan.com/property/kameari-1k-001/',
      type: 'apartment',
      price: 42000,
      deposit: 42000,
      keyMoney: 42000,
      nearestStation: 'Kameari Station',
      walkTime: 8,
      furnished: false,
      foreignerFriendly: true,
      photos: ['https://realestate-japan.com/wp-content/uploads/kameari-01.jpg'],
      descriptionEn: 'Budget 1K in Kameari area. Good train connections to central Tokyo.',
      descriptionJp: '亀有エリアの格安1K。都心への電車アクセス良好。',
      location: 'Kameari',
      lat: 35.7696,
      lng: 139.8514,
    },
    {
      externalId: 'budget-kitasenju-1k-001',
      sourceUrl: 'https://realestate-japan.com/property/kitasenju-1k-001/',
      type: 'apartment',
      price: 48000,
      deposit: 48000,
      keyMoney: 48000,
      nearestStation: 'Kitasenju Station',
      walkTime: 10,
      furnished: false,
      foreignerFriendly: true,
      photos: ['https://realestate-japan.com/wp-content/uploads/kitasenju-01.jpg'],
      descriptionEn: 'Affordable 1K in vibrant Kitasenju. Multiple train lines available.',
      descriptionJp: '賑やかな北千住のお手頃1K。複数の路線利用可能。',
      location: 'Kitasenju',
      lat: 35.7493,
      lng: 139.8052,
    },
    
    // Weekly mansion options
    {
      externalId: 'weekly-tokyu-shibuya-001',
      sourceUrl: 'https://weekly-tokyu.jp/shibuya/',
      type: 'weekly_mansion',
      price: 9800,
      deposit: null,
      keyMoney: null,
      nearestStation: 'Shibuya Station',
      walkTime: 5,
      furnished: true,
      foreignerFriendly: true,
      photos: ['https://weekly-tokyu.jp/images/shibuya-01.jpg'],
      descriptionEn: 'Weekly furnished apartment in Shibuya. Perfect for short business trips or temporary stays.',
      descriptionJp: '渋谷のウィークリー家具付きアパート。短期出張や仮住まいに最適。',
      location: 'Shibuya',
      lat: 35.6595,
      lng: 139.7004,
    },
    {
      externalId: 'weekly-tokyu-shinjuku-001',
      sourceUrl: 'https://weekly-tokyu.jp/shinjuku/',
      type: 'weekly_mansion',
      price: 8500,
      deposit: null,
      keyMoney: null,
      nearestStation: 'Shinjuku Station',
      walkTime: 7,
      furnished: true,
      foreignerFriendly: true,
      photos: ['https://weekly-tokyu.jp/images/shinjuku-01.jpg'],
      descriptionEn: 'Convenient weekly apartment in Shinjuku. All utilities included.',
      descriptionJp: '新宿の便利なウィークリーアパート。光熱費込み。',
      location: 'Shinjuku',
      lat: 35.6938,
      lng: 139.7034,
    },
  ];

  return listings;
}

// Also export a function to get sample listings for testing
export { getCuratedListings as getSampleListings };
